
services:
  cassandra1:
    image: docker.io/bitnami/cassandra:latest
    hostname: cassandra1
    ports:
#      - "7000:7000"
      - "9042:9042"
    volumes:
        - ./docker/cassandra1_data:/bitnami
        - ./docker/cassandra1_conf:/etc/cassandra
    networks:
      - cassandranet
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1, cassandra2
      - CASSANDRA_CLUSTER_NAME=kwiatex-cluster
      - CASSANDRA_DATACENTER = kwiatex-datacenter #no effect datacenter id dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER = cassandra
      - CASSANDRA_PASSWORD=cassandrapassword
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra2:
      image: docker.io/bitnami/cassandra:latest
      hostname: cassandra2
      ports:
#        - "7000:7000"
        - "9043:9042"
      volumes:
        - ./docker/cassandra2_data:/bitnami
        - ./docker/cassandra2_conf:/etc/cassandra
      networks:
        - cassandranet
      environment:
        - CASSANDRA_LISTEN_ADDRESS=cassandra2
        - CASSANDRA_BROADCAST_ADDRESS=cassandra2
        - CASSANDRA_SEEDS=cassandra1,cassandra2
        - CASSANDRA_CLUSTER_NAME=kwiatex-cluster
        - CASSANDRA_DATACENTER = kwiatex-datacenter #no effect datacenter id dc1
        - CASSANDRA_PASSWORD_SEEDER=yes
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        - CASSANDRA_USER = cassandra
        - CASSANDRA_PASSWORD=cassandrapassword
        - MAX_HEAP_SIZE=2G
        - HEAP_NEWSIZE=200M

networks:
  cassandranet: {}


